using System;
using System.Collections.Generic;

namespace StoryboardDemo2
{
    public class AddressBook
    {
        public List<Contact> Contacts
        {
            get;
            set;
        }

        public AddressBook()
        {
            // Generated by なんちゃって個人情報
            // http://kazina.com/dummy/index.html
            Contacts = new List<Contact>
            {
                new Contact { Name = "梅田 美希", Mail = "umeda_miki@example.com", Telephone = "080-2086-4058" },
                new Contact { Name = "松尾 賢二", Mail = "matsuo_kenji@example.com", Telephone = "090-9680-2402" },
                new Contact { Name = "三田 しぼり", Mail = "mita_shibori@example.com", Telephone = "090-6258-2137" },
                new Contact { Name = "半田 亮介", Mail = "hannda_ryousuke@example.com", Telephone = "090-4658-3378" },
                new Contact { Name = "堀 一輝", Mail = "hori_kazuki@example.com", Telephone = "080-8078-4640" },
                new Contact { Name = "野沢 樹里", Mail = "nozawa_juri@example.com", Telephone = "090-4160-3277" },
                new Contact { Name = "児島 貴嶺", Mail = "kojima_takane@example.com", Telephone = "080- 307-6715" },
                new Contact { Name = "川田 寛治", Mail = "kawata_kanji@example.com", Telephone = "080-5775- 346" },
                new Contact { Name = "水崎 満", Mail = "misaki_mitsuru@example.com", Telephone = "080-8116- 227" },
                new Contact { Name = "勝地 竜次", Mail = "katsudi_ryuuji@example.com", Telephone = "090- 840-9736" },
                new Contact { Name = "大塚 研二", Mail = "ootsuka_kenji@example.com", Telephone = "080-7802-5200" },
                new Contact { Name = "橋本 俊介", Mail = "hashimoto_shunsuke@example.com", Telephone = "090-8030-9277" },
                new Contact { Name = "島本 夏空", Mail = "shimamoto_sora@example.com", Telephone = "090-4191-4432" },
                new Contact { Name = "渡辺 美月", Mail = "watanabe_miduki@example.com", Telephone = "090-3652-6314" },
                new Contact { Name = "神野 瞬", Mail = "kamino_shun@example.com", Telephone = "080-4421-5977" },
                new Contact { Name = "島村 祐一", Mail = "shimamura_yuuichi@example.com", Telephone = "090-8971-5757" },
                new Contact { Name = "柄本 敏也", Mail = "emoto_toshiya@example.com", Telephone = "080-7857-9958" },
                new Contact { Name = "美輪 雅彦", Mail = "miwa_masahiko@example.com", Telephone = "080-6823-4215" },
                new Contact { Name = "役所 朝陽", Mail = "yakusho_asahi@example.com", Telephone = "080-6178-6333" },
                new Contact { Name = "坪井 丈雄", Mail = "tsuboi_takeo@example.com", Telephone = "090-8859-3183" },
                new Contact { Name = "池上 小雁", Mail = "ikegami_kogan@example.com", Telephone = "080-4135-8819" },
                new Contact { Name = "今井 克実", Mail = "imai_katsumi@example.com", Telephone = "080-1109-5860" },
                new Contact { Name = "真田 美智子", Mail = "sanada_michiko@example.com", Telephone = "080-  80-7247" },
                new Contact { Name = "加藤 桃子", Mail = "katou_momoko@example.com", Telephone = "090-8989-7163" },
                new Contact { Name = "児島 あおい", Mail = "kojima_aoi@example.com", Telephone = "090-6264-6092" },
                new Contact { Name = "少路 洋介", Mail = "shouji_yousuke@example.com", Telephone = "080-3583-4949" },
                new Contact { Name = "小幡 雅之", Mail = "obata_masayuki@example.com", Telephone = "080-1854- 820" },
                new Contact { Name = "笠原 みゆき", Mail = "kasahara_miyuki@example.com", Telephone = "080-8879-2366" },
                new Contact { Name = "大森 真吾", Mail = "oomori_shingo@example.com", Telephone = "090-6864-6072" },
                new Contact { Name = "石田 かおり", Mail = "ishida_kaori@example.com", Telephone = "080-4699-6532" },
                new Contact { Name = "小平 明", Mail = "kohira_akira@example.com", Telephone = "090-2580- 485" },
                new Contact { Name = "山内 まみ", Mail = "yamauchi_mami@example.com", Telephone = "080-2268-7559" },
                new Contact { Name = "神原 ひかり", Mail = "kannbara_hikari@example.com", Telephone = "090-3618-2180" },
                new Contact { Name = "笠原 里穂", Mail = "kasahara_riho@example.com", Telephone = "080-8846-4073" },
                new Contact { Name = "岩本 三郎", Mail = "iwamoto_saburou@example.com", Telephone = "090-8562-6599" },
                new Contact { Name = "安倍 ひろ子", Mail = "abe_hiroko@example.com", Telephone = "090-4393-7075" },
                new Contact { Name = "加納 碧海", Mail = "kanou_ouga@example.com", Telephone = "080-  42-4516" },
                new Contact { Name = "茂木 あき", Mail = "mogi_aki@example.com", Telephone = "090-7091-3009" },
                new Contact { Name = "関根 米蔵", Mail = "sekine_yonezou@example.com", Telephone = "080-1279-2534" },
                new Contact { Name = "高橋 広司", Mail = "takahashi_kouji@example.com", Telephone = "090-5504-9456" },
                new Contact { Name = "丸山 一", Mail = "maruyama_hajime@example.com", Telephone = "080-4448-1405" },
                new Contact { Name = "高山 法子", Mail = "takayama_noriko@example.com", Telephone = "090-3330-2786" },
                new Contact { Name = "塩谷 隆之介", Mail = "shioya_ryuunosuke@example.com", Telephone = "080-6738-8899" },
                new Contact { Name = "近藤 祐基", Mail = "konndou_yuuki@example.com", Telephone = "090-8083-6510" },
                new Contact { Name = "永野 未華子", Mail = "nagano_mikako@example.com", Telephone = "080-2660-3812" },
                new Contact { Name = "真鍋 浩正", Mail = "manabe_hiromasa@example.com", Telephone = "090-7559-1874" },
                new Contact { Name = "鹿手袋 明", Mail = "shikatebukuro_akira@example.com", Telephone = "080-6092-5991" },
                new Contact { Name = "三浦 優", Mail = "miura_yuu@example.com", Telephone = "090-7715-8526" },
                new Contact { Name = "武藤 美紀", Mail = "mutou_miki@example.com", Telephone = "090-2597-3988" },
                new Contact { Name = "伊藤 浩介", Mail = "itou_kousuke@example.com", Telephone = "080-2469-2745" },
            };
        }
    }
}

